pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('checkout') {
            steps {
                echo 'git checkout'
            }
        }
        stage('build') {
            steps {
                echo 'mvn build'
            }
        }
    }
}


